name: Run Tests

on: [push, pull_request]

jobs:
  golang-tests:
    name: Golang Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Initialize Go module
      run: go mod init NeversitupCodeQuestTasks

    - name: Run Golang Tests
      run: go test ./golang/...


  csharp-tests:
    name: C# Tests
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
  
    - name: Cache NuGet Packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
  
    - name: Run C# Tests
      run: dotnet test ./c-sharp/NeversitupCodeQuestTasks.csproj --no-build --verbosity normal
